blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/your-org/catalyst/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/your-org/catalyst/tree/main/docs
    about: Read the documentation to learn more about Catalyst
  - name: Security Vulnerability
    url: https://github.com/your-org/catalyst/security/policy
    about: Report security vulnerabilities privately
