name: Feature Request
description: Suggest a new feature or enhancement for Catalyst
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving Catalyst! Please describe the feature you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: I'm trying to do X, but Catalyst doesn't support Y...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: I've thought about A and B, but they don't work because...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or screenshots about the feature request
      placeholder: Add any other context, mockups, or examples here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a PR for this feature
